#!/bin/bash

mkdir 100smaller_timestep_light_parameters_rd1_md24



mv actual 100smaller_timestep_light_parameters_rd1_md24
mv binned_data 100smaller_timestep_light_parameters_rd1_md24
mv plots 100smaller_timestep_light_parameters_rd1_md24
mv raw_data 100smaller_timestep_light_parameters_rd1_md24
mv sim_outputs 100smaller_timestep_light_parameters_rd1_md24
mv test_output 100smaller_timestep_light_parameters_rd1_md24
mv theory 100smaller_timestep_light_parameters_rd1_md24

# bash cleanse.sh